# 영단어 뱅크 — 실생활 회화 + 정치 + 사회 테마 1000개
# 알파벳 순 정렬 없이 자연스럽게 섞음

WORDS = [
    # ── 일상 회화 (DAY 1~4) ──────────────────────────────────────────────

    # 감정 / 관계
    ("anxious", "adj", "불안한", "She felt anxious before the job interview."),
    ("furious", "adj", "격노한", "He was furious when he found out the truth."),
    ("relieved", "adj", "안도한", "She was relieved to hear the good news."),
    ("jealous", "adj", "질투하는", "He got jealous when she talked to other guys."),
    ("embarrassed", "adj", "당황한", "I was embarrassed when I forgot his name."),
    ("grateful", "adj", "감사하는", "I'm really grateful for everything you've done."),
    ("overwhelmed", "adj", "압도된", "She felt overwhelmed by all the work."),
    ("upset", "adj", "속상한", "He was upset that no one remembered his birthday."),
    ("confident", "adj", "자신감 있는", "She walked in looking confident and calm."),
    ("content", "adj", "만족한", "He was content with his simple life."),
    ("desperate", "adj", "절박한", "She was desperate to find a solution."),
    ("frustrated", "adj", "좌절한", "I get frustrated when people don't listen."),
    ("stubborn", "adj", "고집스러운", "He's too stubborn to admit he was wrong."),
    ("awkward", "adj", "어색한", "It was really awkward when they ran into each other."),
    ("sincere", "adj", "진심 어린", "She gave a sincere apology."),
    ("affectionate", "adj", "애정 어린", "He's very affectionate with his kids."),
    ("grumpy", "adj", "짜증스러운", "Don't talk to him before coffee — he's grumpy."),
    ("heartbroken", "adj", "상심한", "She was heartbroken after the breakup."),
    ("fond", "adj", "좋아하는", "I'm really fond of her cooking."),
    ("bitter", "adj", "씁쓸한, 원한 품은", "He's still bitter about losing the election."),
    ("trust", "n/v", "신뢰 / 믿다", "Trust takes years to build and seconds to break."),
    ("bond", "n/v", "유대감 / 유대를 맺다", "The shared experience created a strong bond."),
    ("argument", "n", "언쟁", "They had a big argument over money."),
    ("comfort", "v/n", "위로하다 / 위안", "She comforted him after the bad news."),
    ("support", "v/n", "지지하다 / 지지", "I'll support you no matter what."),
    ("betray", "v", "배신하다", "He felt betrayed when his friend lied."),
    ("forgive", "v", "용서하다", "It's hard to forgive, but necessary."),
    ("make up", "v", "화해하다", "They argued but made up the next day."),
    ("drift apart", "v", "멀어지다", "Old friends tend to drift apart over time."),
    ("catch up", "v", "근황을 나누다", "Let's grab coffee and catch up."),
    ("get along", "v", "잘 지내다", "Do you get along with your coworkers?"),
    ("fall out", "v", "사이가 나빠지다", "They fell out over a misunderstanding."),
    ("stand by", "v", "옆을 지키다", "She stood by him through everything."),
    ("let down", "v", "실망시키다", "He let me down when I needed him most."),
    ("look up to", "v", "존경하다", "I've always looked up to my older sister."),
    ("put up with", "v", "참다, 견디다", "I can't put up with his attitude anymore."),
    ("count on", "v", "의지하다", "You can always count on her."),
    ("break up", "v", "헤어지다", "They broke up after two years together."),
    ("reach out", "v", "연락하다", "Don't hesitate to reach out if you need help."),
    ("open up", "v", "마음을 열다", "It took him a while to open up."),

    # 일상 행동 / 생활
    ("commute", "v/n", "통근하다 / 통근", "Her daily commute takes over an hour."),
    ("groceries", "n", "식료품", "I need to pick up groceries on the way home."),
    ("errand", "n", "심부름, 볼일", "I have a few errands to run this afternoon."),
    ("budget", "n/v", "예산 / 예산을 짜다", "We need to stick to our budget this month."),
    ("broke", "adj", "빈털터리인", "I'm totally broke until payday."),
    ("splurge", "v", "돈을 펑펑 쓰다", "I splurged on a new jacket."),
    ("bargain", "n/v", "싸게 사다 / 흥정", "That coat was a real bargain."),
    ("afford", "v", "여유가 되다", "I can't afford a vacation right now."),
    ("rent", "v/n", "빌리다 / 임대료", "Rent in this city is incredibly high."),
    ("landlord", "n", "집주인", "My landlord finally fixed the heater."),
    ("roommate", "n", "룸메이트", "Living with a roommate saves a lot of money."),
    ("chore", "n", "집안일", "We split the household chores evenly."),
    ("commute", "n", "통근길", "The morning commute is unbearable."),
    ("hang out", "v", "어울리다", "Want to hang out this weekend?"),
    ("chill", "v/adj", "쉬다 / 편안한", "Let's just chill at home tonight."),
    ("binge-watch", "v", "몰아보다", "I binge-watched the entire series in one day."),
    ("scroll", "v", "스크롤하다", "I spent an hour scrolling through social media."),
    ("skip", "v", "건너뛰다", "I skipped breakfast this morning."),
    ("rush", "v/n", "서두르다 / 급함", "I'm always in a rush in the morning."),
    ("oversleep", "v", "늦잠 자다", "I overslept and missed my bus."),
    ("pull an all-nighter", "v", "밤을 새다", "He pulled an all-nighter before the exam."),
    ("take a nap", "v", "낮잠 자다", "She always takes a nap after lunch."),
    ("work out", "v", "운동하다", "I try to work out at least three times a week."),
    ("grab a bite", "v", "간단히 먹다", "Want to grab a bite after work?"),
    ("treat", "v/n", "한턱내다 / 간식", "It's my treat — order whatever you want."),
    ("leftovers", "n", "남은 음식", "We had leftovers from dinner last night."),
    ("craving", "n", "갈망", "I have a craving for spicy food."),
    ("stuff", "n/v", "물건 / 채우다", "I have too much stuff in my apartment."),
    ("clutter", "n", "어수선함", "I need to declutter my room this weekend."),
    ("pack", "v", "짐을 싸다", "I haven't started packing for the trip yet."),
    ("cancel", "v", "취소하다", "She had to cancel her plans at the last minute."),
    ("reschedule", "v", "일정을 변경하다", "Can we reschedule our meeting?"),
    ("deadline", "n", "마감 기한", "The deadline is tomorrow and I'm not done."),
    ("procrastinate", "v", "미루다", "Stop procrastinating and just start."),
    ("overwhelming", "adj", "감당하기 힘든", "The amount of homework feels overwhelming."),
    ("distract", "v", "집중을 방해하다", "My phone keeps distracting me from work."),
    ("focus", "v", "집중하다", "I can't focus when it's noisy."),
    ("run out of", "v", "다 떨어지다", "We've run out of coffee again."),
    ("get used to", "v", "익숙해지다", "It takes time to get used to a new city."),
    ("figure out", "v", "알아내다", "I can't figure out how this app works."),

    # 날씨 / 교통 / 여행
    ("humid", "adj", "습한", "Summers here are incredibly humid."),
    ("chilly", "adj", "쌀쌀한", "It's a bit chilly — bring a jacket."),
    ("forecast", "n/v", "예보 / 예측하다", "The forecast says rain all week."),
    ("traffic jam", "n", "교통 체증", "I was stuck in a traffic jam for two hours."),
    ("detour", "n/v", "우회로 / 우회하다", "We had to take a detour because of the accident."),
    ("fare", "n", "요금", "The subway fare went up again."),
    ("transfer", "v/n", "환승하다 / 환승", "You'll need to transfer at the next station."),
    ("delayed", "adj", "지연된", "The flight was delayed by three hours."),
    ("turbulence", "n", "난기류", "We hit some turbulence over the mountains."),
    ("check in", "v", "체크인하다", "You can check in online 24 hours before."),
    ("layover", "n", "경유 대기", "I have a two-hour layover in Singapore."),
    ("jet lag", "n", "시차 피로", "It took me a week to get over the jet lag."),
    ("backpack", "v/n", "배낭여행하다 / 배낭", "She spent a year backpacking through Europe."),
    ("touristy", "adj", "관광객이 많은", "Let's avoid touristy restaurants."),
    ("locals", "n", "현지인들", "Ask the locals for the best food spots."),
    ("itinerary", "n", "여행 일정표", "I've already planned the full itinerary."),
    ("accommodation", "n", "숙소", "We found great accommodation near the beach."),
    ("get around", "v", "돌아다니다", "It's easy to get around by bike here."),
    ("off the beaten path", "adj", "잘 알려지지 않은", "We prefer off-the-beaten-path destinations."),
    ("worth it", "adj", "그럴 만한 가치가 있는", "The hike was long but totally worth it."),

    # 건강 / 의료
    ("symptom", "n", "증상", "What are your symptoms?"),
    ("diagnosis", "n", "진단", "The doctor gave her a diagnosis."),
    ("prescription", "n", "처방전", "You'll need a prescription for that medication."),
    ("side effect", "n", "부작용", "The medication has some mild side effects."),
    ("chronic", "adj", "만성의", "He suffers from chronic back pain."),
    ("immune", "adj", "면역의", "A healthy lifestyle boosts your immune system."),
    ("recover", "v", "회복하다", "She recovered faster than expected."),
    ("surgery", "n", "수술", "He's scheduled for surgery next week."),
    ("vaccine", "n", "백신", "The vaccine is safe and effective."),
    ("burn out", "v", "번아웃되다", "She burned out after working 80 hours a week."),

    # ── 정치 (DAY 5~9) ──────────────────────────────────────────────────

    # 선거 / 정당
    ("election", "n", "선거", "The election results shocked everyone."),
    ("candidate", "n", "후보자", "Three candidates are running for mayor."),
    ("ballot", "n", "투표 용지", "Millions of ballots were cast in the election."),
    ("voter turnout", "n", "투표율", "Voter turnout reached a record high."),
    ("landslide", "n", "압승", "She won the election by a landslide."),
    ("swing vote", "n", "부동표", "The swing vote in this district will decide everything."),
    ("incumbent", "n/adj", "현직자 / 현직의", "The incumbent president is seeking re-election."),
    ("runoff", "n", "결선 투표", "Neither candidate won outright, so there'll be a runoff."),
    ("constituency", "n", "선거구", "He campaigned hard in his home constituency."),
    ("poll", "n/v", "여론조사 / 조사하다", "The latest poll shows a tight race."),
    ("campaign", "n/v", "선거 운동 / 운동하다", "She launched her campaign with a major rally."),
    ("slogan", "n", "슬로건", "Their campaign slogan resonated with voters."),
    ("endorse", "v", "지지하다", "Several major newspapers endorsed the challenger."),
    ("concede", "v", "패배를 인정하다", "The losing candidate refused to concede."),
    ("rigged", "adj", "조작된", "Protesters claimed the election was rigged."),
    ("primary", "n", "예비 선거", "She won the primary by a wide margin."),
    ("coalition", "n", "연립, 연합", "The two parties formed a coalition government."),
    ("partisan", "adj", "당파적인", "The debate became highly partisan."),
    ("grassroots", "adj", "풀뿌리의", "The grassroots campaign mobilized thousands."),
    ("turnout", "n", "투표율, 참여율", "Low turnout often favors the incumbent."),
    ("abstain", "v", "기권하다", "Several lawmakers chose to abstain from the vote."),
    ("hung parliament", "n", "과반 의석 없는 의회", "A hung parliament led to weeks of negotiations."),
    ("proportional representation", "n", "비례 대표", "They're pushing for proportional representation."),
    ("recount", "n/v", "재검표 / 다시 세다", "A recount was demanded in three counties."),
    ("gerrymandering", "n", "게리맨더링", "Gerrymandering has distorted the district map."),
    ("impeach", "v", "탄핵하다", "The president was impeached by the legislature."),
    ("veto", "n/v", "거부권 / 거부하다", "The president vetoed the bill."),
    ("inauguration", "n", "취임식", "The inauguration will be held on January 20th."),
    ("mandate", "n", "위임, 명령", "The party claims a mandate from voters."),
    ("referendum", "n", "국민 투표", "The referendum on independence drew massive turnout."),

    # 국회 / 정책
    ("legislation", "n", "법률, 입법", "New legislation was introduced to address the crisis."),
    ("bill", "n", "법안", "The bill passed with a narrow majority."),
    ("amendment", "n", "수정안, 개정", "An amendment was added to the original bill."),
    ("filibuster", "n", "필리버스터", "The opposition used a filibuster to block the vote."),
    ("bipartisan", "adj", "초당파적인", "The bill received bipartisan support."),
    ("lobbyist", "n", "로비스트", "Lobbyists spent millions influencing the legislation."),
    ("bureaucracy", "n", "관료제", "Cutting through bureaucracy takes time."),
    ("transparency", "n", "투명성", "The public demands more transparency from the government."),
    ("accountability", "n", "책임감", "There's a lack of accountability in the system."),
    ("corruption", "n", "부패", "Corruption scandals have shaken public trust."),
    ("whistleblower", "n", "내부 고발자", "The whistleblower exposed the cover-up."),
    ("crackdown", "n", "단속, 탄압", "The government launched a crackdown on protests."),
    ("executive order", "n", "행정 명령", "The president issued an executive order on immigration."),
    ("sanction", "n/v", "제재 / 제재하다", "Western nations imposed new sanctions."),
    ("embargo", "n", "금수 조치", "The trade embargo has crippled the economy."),
    ("subsidize", "v", "보조금을 지급하다", "The government subsidizes renewable energy."),
    ("austerity", "n", "긴축 재정", "Austerity measures sparked widespread protests."),
    ("fiscal", "adj", "재정의", "The country faces a serious fiscal deficit."),
    ("stimulus", "n", "경기 부양책", "Congress passed a large stimulus package."),
    ("deficit", "n", "적자, 부족분", "The budget deficit has grown each year."),
    ("surplus", "n", "흑자, 잉여", "The country ran a trade surplus for the first time."),
    ("privatize", "v", "민영화하다", "There are plans to privatize the national railway."),
    ("nationalize", "v", "국유화하다", "The government nationalized the failing bank."),
    ("deregulate", "v", "규제를 완화하다", "They moved to deregulate the energy sector."),
    ("welfare", "n", "복지", "Welfare spending has been cut significantly."),
    ("minimum wage", "n", "최저 임금", "Unions are pushing to raise the minimum wage."),
    ("tax break", "n", "세금 감면", "The new law includes major tax breaks for businesses."),
    ("infrastructure", "n", "인프라", "The government plans to invest in infrastructure."),
    ("public sector", "n", "공공 부문", "Public sector workers went on strike."),
    ("red tape", "n", "관료적 형식주의", "Small businesses struggle with excessive red tape."),

    # 외교 / 국제
    ("diplomacy", "n", "외교", "Diplomacy is the best tool to avoid conflict."),
    ("treaty", "n", "조약", "Both countries signed the peace treaty."),
    ("sovereignty", "n", "주권", "They defended their national sovereignty."),
    ("ally", "n/v", "동맹국 / 동맹하다", "The US and South Korea are close allies."),
    ("ceasefire", "n", "휴전", "A fragile ceasefire has been agreed upon."),
    ("sanctions", "n", "제재", "Sanctions have had a severe economic impact."),
    ("bilateral", "adj", "양자 간의", "Bilateral talks are scheduled for next month."),
    ("multilateral", "adj", "다자간의", "A multilateral agreement was reached."),
    ("summit", "n", "정상 회담", "The two leaders met at an emergency summit."),
    ("espionage", "n", "간첩 행위", "He was arrested on charges of espionage."),
    ("geopolitical", "adj", "지정학적", "The region has great geopolitical importance."),
    ("regime", "n", "정권", "The authoritarian regime suppressed dissent."),
    ("authoritarian", "adj", "권위주의적인", "The authoritarian government controls the media."),
    ("autocracy", "n", "독재", "Citizens are fighting against the autocracy."),
    ("democracy", "n", "민주주의", "Democracy requires an informed citizenry."),
    ("populism", "n", "포퓰리즘", "Populism has reshaped politics in many countries."),
    ("nationalist", "n/adj", "민족주의자 / 민족주의의", "A rising nationalist movement swept the country."),
    ("isolationism", "n", "고립주의", "Isolationism has become a political trend."),
    ("intervention", "n", "개입", "Military intervention was seen as a last resort."),
    ("refugee", "n", "난민", "Thousands of refugees have crossed the border."),
    ("asylum", "n", "망명, 피난처", "She applied for asylum after fleeing persecution."),
    ("deportation", "n", "추방", "The deportation policy has drawn criticism."),
    ("extradite", "v", "범죄인을 인도하다", "He was extradited to face trial."),
    ("coup", "n", "쿠데타", "A military coup overthrew the elected government."),
    ("uprising", "n", "봉기", "A popular uprising brought down the regime."),
    ("propaganda", "n", "선전", "State-run media spread propaganda."),
    ("censorship", "n", "검열", "Internet censorship is widespread in some countries."),
    ("disinformation", "n", "허위 정보", "Disinformation campaigns influenced the vote."),
    ("nuclear", "adj", "핵의", "Nuclear disarmament talks have stalled."),
    ("deterrence", "n", "억지", "Nuclear deterrence has maintained an uneasy peace."),

    # 여론 / 시위 / 민주주의
    ("protest", "n/v", "시위 / 항의하다", "Thousands took to the streets to protest."),
    ("demonstration", "n", "시위, 데모", "A peaceful demonstration was held downtown."),
    ("rally", "n", "집회", "The party held a massive rally before the election."),
    ("activist", "n", "활동가", "Human rights activists demand an investigation."),
    ("petition", "n/v", "청원 / 청원하다", "Over a million people signed the online petition."),
    ("civil disobedience", "n", "시민 불복종", "They used civil disobedience to challenge the law."),
    ("riot", "n/v", "폭동 / 폭동을 일으키다", "Riots broke out after the verdict."),
    ("martial law", "n", "계엄령", "The president declared martial law."),
    ("clampdown", "n", "강경 탄압", "The clampdown on protests drew international condemnation."),
    ("dissident", "n", "반체제 인사", "The dissident was arrested and jailed."),
    ("free speech", "n", "언론의 자유", "Free speech is a cornerstone of democracy."),
    ("civil liberties", "n", "시민 자유", "Activists are fighting to protect civil liberties."),
    ("polarization", "n", "양극화", "Political polarization is tearing the country apart."),
    ("backlash", "n", "반발", "The policy met with immediate backlash."),
    ("misinformation", "n", "잘못된 정보", "Misinformation spreads fast on social media."),
    ("fact-check", "v", "사실 확인하다", "We need to fact-check that claim."),
    ("spin", "n/v", "왜곡 / 사실을 왜곡하다", "Politicians are experts at putting spin on bad news."),
    ("rhetoric", "n", "수사학, 말 잔치", "His rhetoric appealed to working-class voters."),
    ("narrative", "n", "서사, 담론", "They're trying to control the political narrative."),
    ("framing", "n", "프레이밍", "The framing of the issue matters enormously."),
    ("public opinion", "n", "여론", "Public opinion has shifted dramatically."),
    ("consensus", "n", "합의", "There's no political consensus on the issue."),
    ("gridlock", "n", "교착 상태", "Congress is in a state of complete gridlock."),
    ("compromise", "n/v", "타협 / 타협하다", "Both sides need to compromise."),
    ("deadlock", "n", "교착 상태", "Talks have reached a deadlock."),
    ("negotiate", "v", "협상하다", "The two sides are still negotiating."),
    ("concession", "n", "양보", "Each side made concessions to reach a deal."),
    ("scapegoat", "n/v", "희생양 / 희생양으로 삼다", "Immigrants were scapegoated for economic problems."),
    ("smear campaign", "n", "흑색선전", "A smear campaign was launched against the candidate."),
    ("whistleblower", "n", "내부 고발자", "The whistleblower risked everything to speak out."),
    ("oversight", "n", "감시, 감독", "Congressional oversight of the agency is essential."),

    # ── 사회 (DAY 10~14) ────────────────────────────────────────────────

    # 불평등 / 인권
    ("inequality", "n", "불평등", "Income inequality continues to widen."),
    ("discrimination", "n", "차별", "Discrimination based on race is illegal."),
    ("privilege", "n", "특권", "He has never had to acknowledge his privilege."),
    ("marginalized", "adj", "소외된", "Marginalized communities need more support."),
    ("systemic", "adj", "구조적인", "Systemic racism is embedded in institutions."),
    ("bias", "n", "편견", "Unconscious bias affects hiring decisions."),
    ("affirmative action", "n", "적극적 우대 정책", "Affirmative action policies remain controversial."),
    ("equity", "n", "형평성", "We should strive for equity, not just equality."),
    ("diversity", "n", "다양성", "Diversity in the workplace improves creativity."),
    ("inclusion", "n", "포용", "Diversity without inclusion is meaningless."),
    ("stereotype", "n/v", "고정 관념 / 고정 관념화하다", "Don't let stereotypes define your expectations."),
    ("prejudice", "n", "편견", "Prejudice can prevent people from reaching their potential."),
    ("empower", "v", "역량을 키우다", "Education empowers people to change their lives."),
    ("oppression", "n", "억압", "They fought against centuries of oppression."),
    ("exploitation", "n", "착취", "Workers suffer from exploitation in some industries."),
    ("solidarity", "n", "연대", "The workers showed solidarity during the strike."),
    ("intersectionality", "n", "교차성", "Intersectionality considers overlapping forms of discrimination."),
    ("social mobility", "n", "사회적 이동성", "Social mobility has declined in many developed countries."),
    ("wealth gap", "n", "빈부 격차", "The wealth gap between rich and poor keeps growing."),
    ("poverty line", "n", "빈곤선", "Millions of children live below the poverty line."),
    ("gentrification", "n", "젠트리피케이션", "Gentrification has pushed out long-time residents."),
    ("homelessness", "n", "노숙", "Homelessness has risen sharply in major cities."),
    ("food insecurity", "n", "식량 불안정", "Food insecurity affects millions of families."),
    ("safety net", "n", "사회 안전망", "A strong safety net protects vulnerable people."),
    ("universal basic income", "n", "기본 소득", "Some economists support universal basic income."),
    ("living wage", "n", "생활 임금", "A living wage should cover basic needs."),
    ("gig economy", "n", "긱 이코노미", "The gig economy offers flexibility but little security."),
    ("labor rights", "n", "노동권", "Workers are striking for better labor rights."),
    ("union", "n", "노동조합", "The union negotiated a better contract."),
    ("strike", "n/v", "파업 / 파업하다", "Workers went on strike for higher wages."),

    # 환경
    ("climate change", "n", "기후 변화", "Climate change is the defining issue of our time."),
    ("carbon footprint", "n", "탄소 발자국", "Reducing your carbon footprint makes a difference."),
    ("greenhouse gas", "n", "온실 가스", "We must cut greenhouse gas emissions dramatically."),
    ("renewable energy", "n", "재생 에너지", "Investment in renewable energy is growing fast."),
    ("fossil fuel", "n", "화석 연료", "We need to phase out fossil fuels."),
    ("deforestation", "n", "삼림 벌채", "Deforestation is destroying critical ecosystems."),
    ("biodiversity", "n", "생물 다양성", "Biodiversity loss is accelerating."),
    ("sustainability", "n", "지속 가능성", "Sustainability should be built into every decision."),
    ("net zero", "n", "탄소 중립", "The company has pledged to reach net zero by 2040."),
    ("carbon tax", "n", "탄소세", "A carbon tax would discourage heavy pollution."),
    ("drought", "n", "가뭄", "The drought has devastated crops across the region."),
    ("wildfire", "n", "산불", "Wildfires destroyed thousands of acres last summer."),
    ("flooding", "n", "홍수", "Severe flooding displaced thousands of residents."),
    ("plastic pollution", "n", "플라스틱 오염", "Plastic pollution is choking our oceans."),
    ("carbon emissions", "n", "탄소 배출", "Carbon emissions need to fall by 50% this decade."),
    ("green energy", "n", "친환경 에너지", "Switching to green energy reduces costs long-term."),
    ("solar panel", "n", "태양광 패널", "They installed solar panels on the roof."),
    ("electric vehicle", "n", "전기차", "Sales of electric vehicles are booming."),
    ("recycle", "v", "재활용하다", "Make sure to recycle paper and plastic."),
    ("compost", "v/n", "퇴비로 만들다 / 퇴비", "We compost our kitchen waste."),
    ("eco-friendly", "adj", "친환경적인", "Consumers are demanding eco-friendly products."),
    ("sustainable", "adj", "지속 가능한", "We need a more sustainable food system."),
    ("pollutant", "n", "오염 물질", "Air pollutants cause serious health problems."),
    ("endangered", "adj", "멸종 위기의", "Many species are now endangered."),
    ("conservation", "n", "보전", "Wildlife conservation requires international effort."),

    # 미디어 / SNS
    ("algorithm", "n", "알고리즘", "The algorithm shows you what it thinks you want."),
    ("echo chamber", "n", "에코 챔버", "Social media creates dangerous echo chambers."),
    ("fake news", "n", "가짜 뉴스", "Fake news spreads faster than real news."),
    ("viral", "adj", "바이럴로 퍼지는", "The video went viral overnight."),
    ("trending", "adj", "트렌딩인", "That topic has been trending all day."),
    ("influencer", "n", "인플루언서", "Brands rely heavily on influencers for marketing."),
    ("troll", "n/v", "악플러 / 악성 댓글 달다", "Internet trolls targeted the journalist."),
    ("cancel culture", "n", "캔슬 컬처", "Cancel culture has sparked a big debate."),
    ("doxxing", "n", "개인 정보 공개", "She was a victim of doxxing and feared for her safety."),
    ("privacy", "n", "개인 정보 보호", "Privacy concerns around AI are growing."),
    ("surveillance", "n", "감시", "Government surveillance of citizens is increasing."),
    ("media bias", "n", "언론 편향", "People across the political spectrum complain about media bias."),
    ("clickbait", "n", "낚시성 기사", "That headline is pure clickbait."),
    ("paywall", "n", "유료 장벽", "Good journalism shouldn't be stuck behind a paywall."),
    ("mainstream media", "n", "주류 언론", "Many people no longer trust mainstream media."),
    ("spin doctor", "n", "홍보 담당자", "Every politician has a team of spin doctors."),
    ("leak", "n/v", "유출 / 유출하다", "A leak revealed the government's secret plan."),
    ("source", "n", "정보 출처", "The journalist refused to reveal her source."),
    ("breaking news", "n", "속보", "Breaking news: a ceasefire has been announced."),
    ("op-ed", "n", "칼럼", "She published an op-ed criticizing the policy."),

    # 교육 / 복지 / 범죄 / 젠더 / 이민
    ("tuition", "n", "수업료", "Tuition fees have risen sharply."),
    ("student loan", "n", "학자금 대출", "Student loan debt is crushing young people."),
    ("dropout", "n/v", "중퇴자 / 중퇴하다", "The dropout rate is highest in low-income areas."),
    ("curriculum", "n", "교육 과정", "The curriculum needs to be modernized."),
    ("literacy", "n", "문해력", "Financial literacy should be taught in school."),
    ("access", "n/v", "접근성 / 접근하다", "Equal access to education is a basic right."),
    ("scholarship", "n", "장학금", "She received a scholarship to study abroad."),
    ("standardized test", "n", "표준화 시험", "Critics say standardized tests are unfair."),
    ("gun control", "n", "총기 규제", "Gun control is one of the most divisive issues."),
    ("crime rate", "n", "범죄율", "The crime rate has fallen in most major cities."),
    ("recidivism", "n", "재범", "Programs to reduce recidivism save taxpayers money."),
    ("incarceration", "n", "수감", "The US has the highest incarceration rate in the world."),
    ("death penalty", "n", "사형", "Many countries have abolished the death penalty."),
    ("drug policy", "n", "마약 정책", "Drug policy reform is gaining momentum."),
    ("rehabilitation", "n", "재활", "Prison should focus on rehabilitation, not punishment."),
    ("gender pay gap", "n", "성별 임금 격차", "The gender pay gap persists across all industries."),
    ("reproductive rights", "n", "재생산권", "Millions marched in defense of reproductive rights."),
    ("LGBTQ+", "n", "성소수자", "LGBTQ+ rights are still under threat in many countries."),
    ("gender identity", "n", "성 정체성", "Respecting gender identity is a matter of dignity."),
    ("patriarchy", "n", "가부장제", "Feminists seek to dismantle the patriarchy."),
    ("sexism", "n", "성차별", "Sexism in the workplace is still widespread."),
    ("immigration", "n", "이민", "Immigration policy is fiercely debated."),
    ("border", "n", "국경", "Thousands cross the border each day."),
    ("undocumented", "adj", "미등록의", "Undocumented immigrants contribute to the economy."),
    ("integrate", "v", "통합하다", "It takes years to integrate into a new society."),
    ("multicultural", "adj", "다문화의", "It's a vibrant multicultural city."),
    ("xenophobia", "n", "외국인 혐오", "Xenophobia is on the rise in some regions."),
    ("hate crime", "n", "혐오 범죄", "Hate crimes have increased significantly."),
    ("human trafficking", "n", "인신매매", "Human trafficking is a global crisis."),
    ("social justice", "n", "사회 정의", "She has dedicated her career to social justice."),

    # ── 뉴스 / 미디어 영어 (DAY 15~17) ─────────────────────────────────

    ("allege", "v", "주장하다, 혐의를 제기하다", "The report alleges widespread corruption."),
    ("accuse", "v", "고발하다", "He was accused of embezzling funds."),
    ("probe", "n/v", "조사 / 조사하다", "Authorities launched a probe into the scandal."),
    ("inquiry", "n", "조사, 심문", "A parliamentary inquiry was announced."),
    ("testimony", "n", "증언", "His testimony contradicted earlier statements."),
    ("verdict", "n", "평결", "The jury delivered its verdict after three days."),
    ("acquit", "v", "무죄 선고하다", "He was acquitted of all charges."),
    ("convict", "v", "유죄 선고하다", "She was convicted of fraud."),
    ("appeal", "v/n", "항소하다 / 항소", "The lawyer filed an appeal immediately."),
    ("indictment", "n", "기소", "A grand jury issued an indictment."),
    ("warrant", "n", "영장", "Police obtained a search warrant."),
    ("casualty", "n", "사상자", "Casualties from the disaster are still unknown."),
    ("fatality", "n", "사망자", "There were no fatalities in the crash."),
    ("crisis", "n", "위기", "The country is in the grip of a political crisis."),
    ("turmoil", "n", "혼란", "Financial markets are in turmoil."),
    ("brink", "n", "직전", "The two countries are on the brink of war."),
    ("escalate", "v", "고조되다", "The conflict has escalated significantly."),
    ("surge", "n/v", "급증 / 급증하다", "There's been a surge in coronavirus cases."),
    ("plummet", "v", "급락하다", "Stock prices plummeted after the announcement."),
    ("soar", "v", "급등하다", "House prices have soared in recent years."),
    ("stall", "v", "교착 상태가 되다", "Negotiations have stalled again."),
    ("unveil", "v", "발표하다", "The government unveiled a new economic plan."),
    ("roll out", "v", "출시하다, 시행하다", "The new policy will be rolled out next month."),
    ("overhaul", "n/v", "전면 개편 / 전면 개편하다", "The healthcare system needs a major overhaul."),
    ("pledge", "v/n", "약속하다 / 서약", "The prime minister pledged to cut taxes."),
    ("vow", "v/n", "맹세하다 / 맹세", "She vowed to fight for justice."),
    ("condemn", "v", "비난하다", "World leaders condemned the attack."),
    ("denounce", "v", "규탄하다", "The opposition denounced the decision."),
    ("hail", "v", "환영하다, 치켜세우다", "The deal was hailed as a major breakthrough."),
    ("slam", "v", "강하게 비판하다", "Critics slammed the government's handling of the crisis."),
    ("row", "n", "논쟁, 말다툼", "A row broke out over the new policy."),
    ("feud", "n/v", "불화 / 불화하다", "A bitter feud has developed between the two leaders."),
    ("standoff", "n", "교착 상태", "A military standoff continues on the border."),
    ("crumble", "v", "무너지다", "Support for the party is crumbling."),
    ("collapse", "v/n", "붕괴하다 / 붕괴", "The coalition government collapsed."),
    ("oust", "v", "쫓아내다", "He was ousted in a party leadership vote."),
    ("resign", "v", "사임하다", "The minister resigned amid the scandal."),
    ("step down", "v", "물러나다", "He stepped down after the allegations surfaced."),
    ("face calls", "v", "요구에 직면하다", "She faces calls to resign from her own party."),
    ("push back", "v", "반발하다", "Lawmakers pushed back against the proposal."),
    ("back down", "v", "물러서다", "The government backed down under pressure."),
    ("clamp down", "v", "강경 단속하다", "Police clamped down on illegal gatherings."),
    ("crack down", "v", "단속을 강화하다", "The government cracked down on tax evasion."),
    ("tighten", "v", "강화하다", "They plan to tighten border controls."),
    ("loosen", "v", "완화하다", "Restrictions are slowly being loosened."),
    ("mount", "v", "고조되다", "Pressure on the president is mounting."),
    ("spark", "v", "촉발하다", "The speech sparked a huge controversy."),
    ("trigger", "v", "촉발하다", "The shooting triggered nationwide protests."),
    ("fuel", "v", "부채질하다", "Inflation is fueling public anger."),
    ("undermine", "v", "약화시키다", "Corruption undermines public trust."),
    ("hamper", "v", "방해하다", "Poor infrastructure hampers economic growth."),
    ("hinder", "v", "방해하다", "Bureaucracy hinders progress."),
    ("boost", "v/n", "끌어올리다 / 상승", "The deal gave the economy a much-needed boost."),
    ("curb", "v/n", "억제하다 / 억제", "Measures to curb inflation are being considered."),
    ("tackle", "v", "해결하다", "Governments must tackle climate change urgently."),
    ("address", "v", "다루다, 해결하다", "The speech failed to address key concerns."),
    ("call for", "v", "촉구하다", "Experts are calling for immediate action."),
    ("warn", "v", "경고하다", "Scientists warn that time is running out."),
    ("cite", "v", "인용하다", "Officials cited security concerns."),
    ("confirm", "v", "확인하다", "The death toll has been confirmed at 30."),
    ("deny", "v", "부인하다", "The government denied any wrongdoing."),
    ("reveal", "v", "드러내다", "The leaked documents revealed the truth."),
    ("expose", "v", "폭로하다", "The report exposed years of cover-up."),
    ("highlight", "v", "부각시키다", "The tragedy highlights the need for reform."),
    ("underscore", "v", "강조하다", "The data underscores the urgency of action."),
    ("reflect", "v", "반영하다", "The poll reflects growing public frustration."),
    ("signal", "v/n", "신호를 보내다 / 신호", "The move signals a major policy shift."),
    ("mark", "v", "나타내다", "The deal marks a turning point in relations."),
    ("represent", "v", "나타내다, 대표하다", "The result represents a massive shift in public opinion."),
    ("come amid", "v", "~속에 나오다", "The announcement comes amid growing tensions."),
    ("come under fire", "v", "비판을 받다", "The decision has come under fire."),
    ("come to light", "v", "밝혀지다", "New evidence has come to light."),
    ("bring to light", "v", "드러내다", "The report brought serious issues to light."),
    ("shed light on", "v", "조명하다", "The study sheds light on the root causes."),
    ("cast doubt on", "v", "의심을 품게 하다", "New evidence casts doubt on his alibi."),
    ("be at stake", "v", "위태롭다", "Democracy itself is at stake."),
    ("take a toll", "v", "타격을 주다", "The war has taken a toll on civilians."),
    ("take effect", "v", "효력이 발생하다", "The new law takes effect in January."),
    ("in the wake of", "prep", "~의 여파로", "Protests erupted in the wake of the verdict."),
    ("amid", "prep", "~가운데", "The talks collapsed amid rising tensions."),
    ("in the run-up to", "prep", "~앞두고", "Security was tight in the run-up to the election."),
    ("on the heels of", "prep", "~의 직후에", "The arrest came on the heels of a major scandal."),
    ("at the forefront", "prep", "선두에서", "She is at the forefront of the climate movement."),
    ("under scrutiny", "prep", "감시를 받고 있는", "The company is under intense scrutiny."),
    ("under pressure", "prep", "압박을 받고 있는", "The government is under pressure to act."),
    ("in limbo", "prep", "불확실한 상태에", "The deal is still in limbo."),
    ("on the table", "prep", "논의 중인", "All options are on the table."),
    ("off the table", "prep", "제외된", "Military action is off the table for now."),

    # ── 고급 회화 표현 (DAY 18~20) ──────────────────────────────────────

    # 원어민이 자주 쓰는 표현
    ("to be honest", "phrase", "솔직히", "To be honest, I don't think it'll work."),
    ("to be fair", "phrase", "공정하게 말하면", "To be fair, he did apologize."),
    ("the thing is", "phrase", "사실은", "The thing is, I'm not sure I trust him."),
    ("at the end of the day", "phrase", "결국에는", "At the end of the day, results matter."),
    ("in the grand scheme of things", "phrase", "큰 그림에서 보면", "In the grand scheme of things, it doesn't matter."),
    ("all things considered", "phrase", "모든 것을 고려하면", "All things considered, it went pretty well."),
    ("when push comes to shove", "phrase", "결정적인 순간에", "When push comes to shove, she'll do the right thing."),
    ("in the long run", "phrase", "장기적으로", "In the long run, it's better to invest than save."),
    ("on second thought", "phrase", "다시 생각해보니", "On second thought, let's cancel the meeting."),
    ("by the same token", "phrase", "마찬가지로", "By the same token, we should help others too."),
    ("for what it's worth", "phrase", "참고로 말하자면", "For what it's worth, I think you're right."),
    ("come to think of it", "phrase", "생각해보니", "Come to think of it, I've met her before."),
    ("as far as I can tell", "phrase", "내가 알기로는", "As far as I can tell, no one noticed."),
    ("as a matter of fact", "phrase", "사실은", "As a matter of fact, I know her personally."),
    ("needless to say", "phrase", "말할 필요도 없이", "Needless to say, it was a disaster."),
    ("believe it or not", "phrase", "믿기 어렵겠지만", "Believe it or not, I've never seen snow."),
    ("more often than not", "phrase", "대부분의 경우", "More often than not, the first impression matters."),
    ("the bottom line", "phrase", "핵심은", "The bottom line is: we need more funding."),
    ("cut to the chase", "phrase", "본론으로 가다", "Let's cut to the chase — what do you want?"),
    ("beat around the bush", "phrase", "빙 돌려 말하다", "Stop beating around the bush and tell me."),
    ("on the fence", "phrase", "중립 입장인", "I'm still on the fence about voting for him."),
    ("sit on the fence", "phrase", "결정을 못 내리다", "You can't sit on the fence forever."),
    ("make a case for", "phrase", "주장을 펼치다", "She made a strong case for raising taxes."),
    ("pick apart", "phrase", "낱낱이 비판하다", "Critics picked apart every word of the speech."),
    ("make a point", "phrase", "요점을 말하다", "He made a valid point about job losses."),
    ("get to the point", "phrase", "요점을 말하다", "Can you please get to the point?"),
    ("talk someone out of", "phrase", "설득해서 못 하게 하다", "She talked him out of quitting."),
    ("talk someone into", "phrase", "설득하다", "He talked me into attending the event."),
    ("play devil's advocate", "phrase", "반대 논리를 내세우다", "Let me play devil's advocate for a moment."),
    ("give the benefit of the doubt", "phrase", "일단 믿어주다", "I'll give you the benefit of the doubt this time."),
    ("turn a blind eye", "phrase", "못 본 척하다", "The government turned a blind eye to corruption."),
    ("the elephant in the room", "phrase", "공공연한 비밀", "No one mentioned the elephant in the room."),
    ("a double-edged sword", "phrase", "양날의 검", "Social media is a double-edged sword."),
    ("a slippery slope", "phrase", "미끄러운 경사면", "Critics called the policy a slippery slope."),
    ("the tip of the iceberg", "phrase", "빙산의 일각", "What we know is just the tip of the iceberg."),
    ("read between the lines", "phrase", "행간을 읽다", "You have to read between the lines."),
    ("take with a grain of salt", "phrase", "믿지 않고 듣다", "Take that poll with a grain of salt."),
    ("blow out of proportion", "phrase", "과장하다", "The media blew the story out of proportion."),
    ("jump to conclusions", "phrase", "섣불리 결론 내리다", "Don't jump to conclusions."),
    ("lose sight of", "phrase", "잊다, 놓치다", "Don't lose sight of the bigger picture."),
    ("have a point", "phrase", "일리가 있다", "You have a point — it's not that simple."),
    ("rub someone the wrong way", "phrase", "거슬리다", "His arrogance rubs people the wrong way."),
    ("be on the same page", "phrase", "같은 생각이다", "We need to make sure everyone is on the same page."),
    ("beg the question", "phrase", "의문을 갖게 하다", "This begs the question: why did no one speak up?"),
    ("shed light", "phrase", "빛을 비추다", "New research sheds light on the issue."),
    ("go hand in hand", "phrase", "함께 하다", "Freedom and responsibility go hand in hand."),
    ("pave the way", "phrase", "길을 열다", "This decision paves the way for future talks."),
    ("take center stage", "phrase", "중심이 되다", "Climate change has taken center stage."),
    ("spark debate", "phrase", "논란을 일으키다", "The ruling sparked fierce debate."),
    ("fuel speculation", "phrase", "추측을 부추기다", "His silence fueled speculation."),
    ("draw a line", "phrase", "선을 긋다", "We need to draw a line somewhere."),
    ("stand one's ground", "phrase", "주장을 굽히지 않다", "She stood her ground despite the criticism."),
    ("hold one's ground", "phrase", "자리를 지키다", "The troops held their ground."),
    ("back up", "phrase", "지지하다, 뒷받침하다", "Do you have any evidence to back that up?"),
    ("bring up", "phrase", "언급하다", "He brought up the issue at the meeting."),
    ("follow through", "phrase", "끝까지 해내다", "Politicians rarely follow through on promises."),
    ("carry out", "phrase", "실행하다", "The attack was carried out by extremists."),
    ("carry weight", "phrase", "무게가 있다", "Her opinion carries a lot of weight."),
    ("hold accountable", "phrase", "책임지게 하다", "We must hold leaders accountable."),
    ("set the record straight", "phrase", "사실을 바로잡다", "He called a press conference to set the record straight."),
    ("speak out", "phrase", "목소리를 내다", "Few were willing to speak out against the regime."),
    ("step up", "phrase", "나서다, 역할을 다하다", "The government needs to step up its response."),
    ("come forward", "phrase", "나서다", "A witness came forward with new information."),
    ("take a stand", "phrase", "입장을 취하다", "It's time to take a stand on this issue."),
    ("lay the groundwork", "phrase", "기반을 닦다", "This agreement lays the groundwork for peace."),
    ("be in hot water", "phrase", "곤경에 처하다", "The minister is in hot water over the scandal."),
    ("walk a tightrope", "phrase", "아슬아슬한 줄타기를 하다", "The president is walking a political tightrope."),
    ("pick up steam", "phrase", "탄력을 받다", "The movement is picking up steam."),
    ("gain traction", "phrase", "지지를 얻다", "The idea is gaining traction."),
    ("lose ground", "phrase", "입지를 잃다", "The ruling party is losing ground."),
    ("hold sway", "phrase", "지배하다", "Old attitudes still hold sway in some areas."),
    ("make headway", "phrase", "진전을 이루다", "Negotiators are finally making headway."),
    ("reach a tipping point", "phrase", "임계점에 도달하다", "Tensions have reached a tipping point."),
    ("paper over", "phrase", "덮어두다", "The deal papers over deep divisions."),
    ("fly under the radar", "phrase", "주목을 피하다", "The bill flew under the radar initially."),
    ("catch off guard", "phrase", "허를 찌르다", "The announcement caught everyone off guard."),
    ("put on the spot", "phrase", "곤란하게 만들다", "The reporter's question put him on the spot."),
    ("go off-script", "phrase", "즉흥 발언을 하다", "The president went off-script during the speech."),
    ("leave the door open", "phrase", "여지를 남기다", "She left the door open for future talks."),
    ("draw a distinction", "phrase", "구분을 짓다", "We need to draw a clear distinction."),
    ("bridge the gap", "phrase", "간극을 좁히다", "Both sides are trying to bridge the gap."),
    ("close ranks", "phrase", "단결하다", "The party closed ranks after the scandal."),
    ("rock the boat", "phrase", "파란을 일으키다", "Nobody wanted to rock the boat."),
    ("go against the grain", "phrase", "흐름에 역행하다", "Her views go against the grain."),
    ("toe the line", "phrase", "규율을 따르다", "Party members are expected to toe the line."),
    ("cross the line", "phrase", "선을 넘다", "That comment crossed a line."),
    ("raise the bar", "phrase", "기준을 높이다", "The new standards raise the bar for everyone."),
    ("move the goalposts", "phrase", "규칙을 바꾸다", "Every time we get close, they move the goalposts."),
    ("fall short", "phrase", "부족하다", "The plan falls short of what's needed."),
    ("go the extra mile", "phrase", "한발 더 나아가다", "She always goes the extra mile."),
    ("come a long way", "phrase", "많이 발전했다", "We've come a long way on civil rights."),
    ("turn the tide", "phrase", "판세를 바꾸다", "The speech turned the tide of public opinion."),
    ("pave the way for", "phrase", "~을 위한 길을 열다", "The peace talks paved the way for cooperation."),
    ("bite the bullet", "phrase", "결단을 내리다", "Sometimes you just have to bite the bullet."),
    ("on thin ice", "phrase", "불안한 상황에", "The government is already on thin ice."),
    ("clear the air", "phrase", "오해를 풀다", "Both sides met to clear the air."),
    ("sweep under the rug", "phrase", "묵살하다", "The allegations were swept under the rug."),
    ("call the shots", "phrase", "결정권을 갖다", "Who's really calling the shots here?"),
    ("behind closed doors", "phrase", "비밀리에", "The real negotiations happen behind closed doors."),
    ("off the record", "phrase", "비공식적으로", "He told me off the record that he was resigning."),
    ("on the record", "phrase", "공식적으로", "I'm saying this on the record."),
    ("play hardball", "phrase", "강경하게 나오다", "They're playing hardball in the negotiations."),
    ("at a crossroads", "phrase", "기로에 서 있는", "The country is at a crossroads."),
    ("watershed moment", "phrase", "전환점", "This ruling is a watershed moment."),

    # ── 추가 일상 회화 ────────────────────────────────────────────────────
    ("drained", "adj", "기력이 빠진", "I feel completely drained after that meeting."),
    ("hyped", "adj", "신난, 기대에 찬", "Everyone is hyped about the new season."),
    ("pumped", "adj", "의욕에 넘치는", "I'm pumped for tomorrow's game."),
    ("worn out", "adj", "지쳐 버린", "She was worn out after the long shift."),
    ("stressed out", "adj", "극도로 스트레스받은", "He's been really stressed out lately."),
    ("laid-back", "adj", "느긋한", "He has a very laid-back personality."),
    ("uptight", "adj", "긴장한, 까다로운", "She's too uptight about small mistakes."),
    ("easygoing", "adj", "여유 있는", "My roommate is really easygoing to live with."),
    ("high-strung", "adj", "신경질적인", "She's always been a bit high-strung."),
    ("moody", "adj", "기분이 오락가락하는", "He tends to get moody under pressure."),
    ("nag", "v/n", "잔소리하다 / 잔소리꾼", "Stop nagging me about the dishes."),
    ("clingy", "adj", "집착하는", "She found him a bit too clingy."),
    ("toxic", "adj", "독성의, 해로운", "That relationship was really toxic."),
    ("manipulative", "adj", "조종하는", "He realized she was being manipulative."),
    ("genuine", "adj", "진정한", "She gave me a genuine compliment."),
    ("upfront", "adj", "솔직한", "Just be upfront about how you feel."),
    ("blunt", "adj", "직설적인", "She's very blunt — she says exactly what she thinks."),
    ("tactful", "adj", "눈치 있는", "Try to be tactful when giving feedback."),
    ("resonate", "v", "공감을 얻다", "His message really resonated with young voters."),
    ("vibe", "n", "분위기, 느낌", "I got a weird vibe from that place."),
    ("hang on", "v", "잠깐 기다리다", "Hang on, let me check my phone."),
    ("hold on", "v", "잠깐만요", "Hold on — I didn't say that."),
    ("fair enough", "phrase", "그럴 만해", "Fair enough — I see your point."),
    ("no wonder", "phrase", "당연하지", "No wonder she was upset."),
    ("out of the blue", "phrase", "갑자기", "He called me out of the blue."),
    ("once in a while", "phrase", "가끔", "We should catch up once in a while."),
    ("every now and then", "phrase", "때때로", "I check in on him every now and then."),
    ("on and off", "phrase", "들쑥날쑥하게", "They've been dating on and off for years."),
    ("all of a sudden", "phrase", "갑자기", "All of a sudden, the lights went out."),
    ("sooner or later", "phrase", "조만간", "Sooner or later, you'll have to decide."),
    ("no big deal", "phrase", "별거 아냐", "It's no big deal — don't stress about it."),
    ("a big deal", "phrase", "중요한 일", "This promotion is a really big deal for her."),
    ("kind of", "phrase", "좀, 약간", "I kind of knew something was wrong."),
    ("sort of", "phrase", "어느 정도", "She's sort of in between jobs right now."),
    ("for the record", "phrase", "명심하기 바라지만", "For the record, I never agreed to that."),
    ("off the top of my head", "phrase", "즉석에서", "Off the top of my head, I'd say about fifty."),
    ("on the spot", "phrase", "즉석에서", "She had to answer on the spot."),
    ("to make matters worse", "phrase", "설상가상으로", "To make matters worse, it started raining."),
    ("let alone", "phrase", "~은 커녕", "He can't afford rent, let alone a vacation."),
    ("not to mention", "phrase", "게다가", "It was expensive, not to mention inconvenient."),
    ("first and foremost", "phrase", "무엇보다도 먼저", "First and foremost, we need to stay calm."),
    ("last but not least", "phrase", "마지막으로 중요한 것은", "Last but not least, thank you all for coming."),
    ("so to speak", "phrase", "말하자면", "He's our unofficial leader, so to speak."),
    ("in other words", "phrase", "다시 말해서", "In other words, the project is on hold."),
    ("that being said", "phrase", "그렇긴 하지만", "That being said, we should keep trying."),
    ("having said that", "phrase", "그렇긴 하지만", "Having said that, there are still risks."),
    ("in hindsight", "phrase", "돌이켜보면", "In hindsight, I should've listened."),
    ("in retrospect", "phrase", "되돌아보면", "In retrospect, it was a mistake."),
    ("out of hand", "phrase", "손쓸 수 없이", "The situation got out of hand quickly."),
    ("under the circumstances", "phrase", "상황을 감안하면", "You did well under the circumstances."),
    ("in a nutshell", "phrase", "한마디로", "In a nutshell, the plan failed."),
    ("give or take", "phrase", "대략", "It'll take about two hours, give or take."),
    ("more or less", "phrase", "어느 정도", "That's more or less what happened."),
    ("by and large", "phrase", "대체로", "By and large, the event was a success."),
    ("in the meantime", "phrase", "그사이에", "In the meantime, let's keep working."),
    ("for the time being", "phrase", "당분간", "Let's leave it as it is for the time being."),
    ("as of now", "phrase", "현재로서는", "As of now, the deal has not been confirmed."),
    ("as it stands", "phrase", "현 상황으로는", "As it stands, the bill has no chance of passing."),
    ("keep in mind", "phrase", "명심하다", "Keep in mind that this is just a draft."),
    ("bear in mind", "phrase", "명심하다", "Bear in mind that plans can change."),
    ("take into account", "phrase", "고려하다", "We need to take all factors into account."),
    ("take into consideration", "phrase", "고려하다", "Please take our concerns into consideration."),

    # ── 추가 정치 어휘 ────────────────────────────────────────────────────
    ("biased", "adj", "편향된", "The coverage was clearly biased."),
    ("neutral", "adj", "중립적인", "The moderator tried to remain neutral."),
    ("transparent", "adj", "투명한", "The process must be transparent."),
    ("undemocratic", "adj", "비민주적인", "Critics called the decision undemocratic."),
    ("unconstitutional", "adj", "위헌의", "The law was ruled unconstitutional."),
    ("overturn", "v", "뒤집다", "The court overturned the decision."),
    ("uphold", "v", "유지하다, 지지하다", "The court upheld the original ruling."),
    ("rule", "v", "판결하다", "The judge ruled in her favor."),
    ("sue", "v", "고소하다", "She threatened to sue the newspaper."),
    ("lawsuit", "n", "소송", "The company faces a major lawsuit."),
    ("settlement", "n", "합의", "They reached an out-of-court settlement."),
    ("injunction", "n", "금지 명령", "The court issued an injunction."),
    ("executive", "n/adj", "행정부 / 행정의", "The executive branch enforces the law."),
    ("judiciary", "n", "사법부", "An independent judiciary is vital for democracy."),
    ("legislature", "n", "입법부", "The legislature passed the budget."),
    ("separation of powers", "n", "삼권 분립", "Separation of powers prevents abuse of authority."),
    ("checks and balances", "n", "견제와 균형", "Checks and balances keep power in check."),
    ("rule of law", "n", "법치주의", "The rule of law must be respected."),
    ("due process", "n", "적법한 절차", "Everyone deserves due process."),
    ("presumption of innocence", "n", "무죄 추정", "The presumption of innocence is fundamental."),
    ("habeas corpus", "n", "인신 보호 영장", "Habeas corpus protects against unlawful detention."),
    ("civil rights", "n", "시민권", "The civil rights movement changed history."),
    ("minority rights", "n", "소수자 권리", "Protecting minority rights is non-negotiable."),
    ("freedom of assembly", "n", "집회의 자유", "Freedom of assembly was restricted."),
    ("freedom of press", "n", "언론 자유", "Freedom of the press is under threat."),
    ("censure", "v/n", "견책하다 / 견책", "The senator was formally censured."),
    ("subpoena", "n/v", "소환장 / 소환하다", "He was subpoenaed to testify before Congress."),
    ("redact", "v", "삭제하다, 편집하다", "Key sections of the document were redacted."),
    ("pardon", "v/n", "사면하다 / 사면", "The outgoing president issued several pardons."),
    ("commute", "v", "감형하다", "Her sentence was commuted to five years."),
    ("extort", "v", "갈취하다", "He was accused of extorting local businesses."),
    ("bribe", "v/n", "뇌물을 주다 / 뇌물", "Officials were caught accepting bribes."),
    ("embezzle", "v", "횡령하다", "He embezzled millions in public funds."),
    ("money laundering", "n", "돈세탁", "The investigation uncovered money laundering."),
    ("conflict of interest", "n", "이해 충돌", "She recused herself due to a conflict of interest."),
    ("abuse of power", "n", "권력 남용", "He was removed from office for abuse of power."),
    ("cover-up", "n", "은폐", "Investigators uncovered a systematic cover-up."),
    ("quid pro quo", "n", "대가성", "The investigation focused on the alleged quid pro quo."),
    ("patronage", "n", "낙하산, 정치적 임명", "Patronage appointments have long been criticized."),
    ("nepotism", "n", "친족 등용", "Nepotism is rife in some administrations."),
    ("cronyism", "n", "연줄 등용", "Cronyism undermines merit-based governance."),
    ("strongman", "n", "강권 통치자", "The country is now led by a strongman."),
    ("junta", "n", "군사 정권", "The military junta suspended the constitution."),
    ("theocracy", "n", "신정 정치", "The country has elements of theocracy."),
    ("left-wing", "adj", "좌파의", "Left-wing activists organized the march."),
    ("right-wing", "adj", "우파의", "Right-wing media promoted the story."),
    ("centrist", "adj/n", "중도의 / 중도파", "She ran as a centrist candidate."),
    ("radical", "adj", "급진적인", "Radical reforms were proposed."),
    ("moderate", "adj/n", "온건한 / 온건파", "Moderates within the party opposed the move."),
    ("hardliner", "n", "강경파", "Hardliners in the government blocked the deal."),
    ("hawk", "n", "매파", "The hawks in the cabinet pushed for military action."),
    ("dove", "n", "비둘기파", "Doves argued for a diplomatic solution."),
    ("swing state", "n", "경합 주", "Ohio is a crucial swing state."),
    ("lame duck", "n", "레임덕", "He's a lame duck president in his final months."),
    ("spin", "n", "왜곡", "That press release was pure spin."),
    ("fearmongering", "n", "공포 조장", "The opposition accused the ruling party of fearmongering."),
    ("dog whistle", "n", "암묵적 메시지", "That was clearly a dog whistle to his base."),
    ("gaslighting", "n", "가스라이팅", "The administration's response amounted to gaslighting."),
    ("pivot", "v/n", "전환하다 / 전환", "The candidate pivoted to economic issues."),
    ("double down", "v", "기존 입장을 더 강화하다", "Despite criticism, she doubled down on her stance."),
    ("walk back", "v", "발언을 철회하다", "He later walked back the controversial statement."),
    ("flip-flop", "v/n", "말을 바꾸다 / 입장 번복", "She was accused of flip-flopping on the issue."),
    ("grandstand", "v", "쇼를 하다", "Politicians love to grandstand during hearings."),
    ("pander", "v", "아첨하다", "Critics accused him of pandering to the base."),
    ("virtue signal", "v", "도덕적 우월감을 과시하다", "He was accused of virtue signaling."),
    ("political capital", "n", "정치적 자원", "She spent her political capital on the reform."),
    ("base", "n", "핵심 지지층", "The policy was designed to appeal to the base."),
    ("swing voter", "n", "부동층 유권자", "Winning over swing voters is the key."),
    ("echo chamber", "n", "에코 챔버", "Political echo chambers deepen divisions."),

    # ── 추가 사회 어휘 ────────────────────────────────────────────────────
    ("burnout", "n", "번아웃", "Teacher burnout is at an all-time high."),
    ("mental health", "n", "정신 건강", "Mental health awareness has improved."),
    ("stigma", "n", "낙인", "There is still a stigma around mental illness."),
    ("destigmatize", "v", "낙인을 없애다", "We need to destigmatize seeking help."),
    ("self-care", "n", "자기 관리", "Self-care is more than bubble baths."),
    ("therapy", "n", "치료, 상담", "She started therapy after the breakup."),
    ("trauma", "n", "트라우마", "Childhood trauma can affect adult behavior."),
    ("trigger", "n", "트리거, 자극", "That topic is a trigger for some people."),
    ("resilience", "n", "회복력", "Young people showed remarkable resilience."),
    ("cope", "v", "대처하다", "People cope with grief in different ways."),
    ("taboo", "n/adj", "금기 / 금기의", "Mental illness is no longer taboo."),
    ("opioid", "n", "오피오이드", "The opioid crisis has devastated communities."),
    ("overdose", "n/v", "과다 복용 / 과다 복용하다", "Drug overdose deaths have skyrocketed."),
    ("addiction", "n", "중독", "Addiction is a public health issue."),
    ("harm reduction", "n", "위해 감소", "Harm reduction strategies save lives."),
    ("aging population", "n", "고령화 인구", "An aging population strains the pension system."),
    ("birth rate", "n", "출생률", "The birth rate has fallen sharply."),
    ("demographic", "n/adj", "인구 통계 / 인구의", "The demographic shift will reshape politics."),
    ("life expectancy", "n", "기대 수명", "Life expectancy has increased globally."),
    ("universal healthcare", "n", "전국민 의료보험", "Universal healthcare is still debated in the US."),
    ("privatization", "n", "민영화", "The privatization of hospitals is controversial."),
    ("overcrowded", "adj", "과밀한", "Overcrowded prisons are a major problem."),
    ("underfunded", "adj", "자금 부족의", "Public schools are consistently underfunded."),
    ("neglect", "n/v", "방치 / 방치하다", "Child neglect is a serious social issue."),
    ("at-risk", "adj", "위험에 처한", "At-risk youth need more support."),
    ("foster care", "n", "위탁 양육", "Thousands of children are in foster care."),
    ("domestic violence", "n", "가정 폭력", "Domestic violence cases surged during lockdown."),
    ("shelter", "n", "피난처, 보호소", "Victims were taken to a women's shelter."),
    ("grassroots", "adj/n", "풀뿌리의 / 풀뿌리 운동", "The grassroots movement is gaining momentum."),
    ("nonprofit", "n/adj", "비영리 / 비영리의", "She works for a nonprofit focused on education."),
    ("volunteerism", "n", "자원봉사 정신", "Volunteerism strengthens communities."),
    ("civic engagement", "n", "시민 참여", "Civic engagement is essential for democracy."),
    ("social cohesion", "n", "사회적 결속", "Inequality threatens social cohesion."),
    ("community", "n", "지역 사회", "A strong community can overcome hardship."),
    ("mainstream", "n/adj", "주류 / 주류의", "The idea has entered the mainstream."),
    ("subculture", "n", "하위문화", "Youth subcultures often challenge norms."),
    ("norm", "n", "규범", "Social norms are constantly evolving."),
    ("taboo", "n", "금기", "Talking about death is a cultural taboo."),
    ("social contract", "n", "사회 계약", "The social contract has broken down."),
    ("institution", "n", "제도, 기관", "Public trust in institutions is declining."),
    ("accountability", "n", "책임", "Institutions must be held to account."),
    ("erosion", "n", "침식, 약화", "There is a gradual erosion of trust."),
    ("decay", "n/v", "쇠퇴 / 쇠퇴하다", "Social decay is visible in many cities."),
    ("flourish", "v", "번성하다", "Democracy flourishes when people participate."),
    ("crumble", "v", "무너지다", "Social trust is crumbling."),
    ("unravel", "v", "해체되다", "The welfare state is slowly unraveling."),
    ("fracture", "v/n", "분열하다 / 균열", "Society has fractured along political lines."),
    ("divide", "n/v", "분열 / 나누다", "The racial divide remains wide."),
    ("bridge", "v", "극복하다", "We must try to bridge our differences."),
    ("reconcile", "v", "화해하다", "It's hard to reconcile the two perspectives."),
    ("dialogue", "n", "대화", "We need an honest national dialogue."),
    ("tolerance", "n", "관용", "Building tolerance takes time and effort."),
    ("coexist", "v", "공존하다", "Different communities can coexist peacefully."),
    ("integrate", "v", "통합하다", "Schools play a key role in integrating communities."),
    ("segregate", "v", "분리하다", "Schools were historically segregated."),
    ("assimilation", "n", "동화", "Full assimilation is not always desirable."),
    ("cultural identity", "n", "문화적 정체성", "Preserving cultural identity matters to migrants."),
    ("heritage", "n", "문화유산", "We must protect our shared heritage."),
    ("indigenous", "adj", "원주민의", "Indigenous rights have been ignored for centuries."),
    ("colonialism", "n", "식민주의", "The effects of colonialism are still felt today."),
    ("reparations", "n", "배상", "Reparations for historical wrongs remain debated."),
    ("land rights", "n", "토지권", "Indigenous communities are fighting for land rights."),
    ("apartheid", "n", "아파르트헤이트", "South Africa dismantled apartheid in 1994."),
    ("segregation", "n", "인종 차별", "Racial segregation was legally ended in 1964."),
    ("civil war", "n", "내전", "The civil war left deep scars."),
    ("atrocity", "n", "잔학 행위", "Atrocities were committed on both sides."),
    ("genocide", "n", "집단 학살", "The world failed to prevent the genocide."),
    ("human rights violation", "n", "인권 침해", "UN investigators found evidence of human rights violations."),
    ("impunity", "n", "처벌받지 않음", "Abuses continue with impunity."),
    ("justice", "n", "정의", "Victims are still seeking justice."),
    ("accountability", "n", "책임", "There can be no peace without accountability."),
    ("war crime", "n", "전쟁 범죄", "He faces charges of war crimes."),
    ("tribunal", "n", "재판소", "An international tribunal was established."),
    ("sanction", "n", "제재", "Targeted sanctions were imposed on officials."),
    ("boycott", "n/v", "불매 운동 / 불매하다", "Consumers launched a boycott of the brand."),
    ("divestment", "n", "투자 철수", "Students are demanding divestment from fossil fuels."),
    ("protest vote", "n", "저항 투표", "Many cast a protest vote against the main parties."),
    ("apathy", "n", "무관심", "Political apathy is rising among young people."),
    ("cynicism", "n", "냉소주의", "Growing cynicism about politics is worrying."),
    ("disillusionment", "n", "환멸", "There is widespread disillusionment with the system."),
    ("disenchanted", "adj", "환멸을 느끼는", "Voters are disenchanted with both parties."),
    ("disengage", "v", "이탈하다", "Young people are disengaging from politics."),
    ("empower", "v", "역량을 키우다", "Civic education empowers communities."),

    # ── 추가 뉴스 / 미디어 영어 ───────────────────────────────────────────
    ("fallout", "n", "파장, 여파", "The political fallout from the scandal continues."),
    ("repercussion", "n", "반향, 여파", "The decision had serious repercussions."),
    ("ramification", "n", "결과, 파급 효과", "The ramifications of the ruling are still unclear."),
    ("implication", "n", "함의", "The implications are far-reaching."),
    ("precedent", "n", "선례", "This ruling sets a dangerous precedent."),
    ("landmark", "adj/n", "획기적인 / 이정표", "It was a landmark ruling."),
    ("groundbreaking", "adj", "획기적인", "The study is groundbreaking."),
    ("unprecedented", "adj", "전례 없는", "The decision is unprecedented."),
    ("sweeping", "adj", "광범위한", "The government announced sweeping reforms."),
    ("far-reaching", "adj", "광범위한 영향을 미치는", "The changes will have far-reaching consequences."),
    ("wide-ranging", "adj", "광범위한", "The investigation was wide-ranging."),
    ("comprehensive", "adj", "포괄적인", "A comprehensive review was conducted."),
    ("stringent", "adj", "엄격한", "Stringent measures were put in place."),
    ("watered-down", "adj", "희석된", "Critics called it a watered-down compromise."),
    ("controversial", "adj", "논란이 되는", "The policy remains controversial."),
    ("polarizing", "adj", "의견을 갈라놓는", "It's a deeply polarizing issue."),
    ("contentious", "adj", "논쟁이 많은", "The issue remains highly contentious."),
    ("divisive", "adj", "분열을 일으키는", "The rhetoric has been deeply divisive."),
    ("hotly debated", "adj", "뜨겁게 논의되는", "The topic is hotly debated."),
    ("mounting", "adj", "고조되는", "There is mounting pressure on the president."),
    ("looming", "adj", "다가오는", "A looming crisis must be addressed."),
    ("brewing", "adj", "고조되고 있는", "A political storm is brewing."),
    ("imminent", "adj", "임박한", "An imminent threat was reported."),
    ("unfolding", "adj", "전개 중인", "We're watching an unfolding disaster."),
    ("ensue", "v", "뒤따르다", "Protests ensued after the verdict."),
    ("erupt", "v", "폭발하다", "Violence erupted in the streets."),
    ("descend into", "v", "~로 빠져들다", "The city descended into chaos."),
    ("spiral out of control", "v", "통제 불능이 되다", "The situation spiraled out of control."),
    ("take a turn for the worse", "v", "악화되다", "Things took a turn for the worse."),
    ("hit a new low", "v", "최저점을 찍다", "Approval ratings have hit a new low."),
    ("reach a boiling point", "v", "임계점에 달하다", "Tensions reached a boiling point."),
    ("be on the verge of", "v", "~의 직전이다", "The talks are on the verge of collapse."),
    ("be plagued by", "v", "~에 시달리다", "The project has been plagued by delays."),
    ("grapple with", "v", "씨름하다", "Leaders are grappling with the crisis."),
    ("navigate", "v", "헤쳐나가다", "The country must navigate difficult times."),
    ("weather", "v", "헤쳐나가다", "They managed to weather the financial storm."),
    ("bounce back", "v", "반등하다", "The economy is starting to bounce back."),
    ("brace for", "v", "준비하다", "The country is bracing for a recession."),
    ("call into question", "v", "의문을 제기하다", "The scandal calls his integrity into question."),
    ("be called to account", "v", "책임을 묻다", "Officials were called to account."),
    ("fall from grace", "v", "몰락하다", "The once-popular leader has fallen from grace."),
    ("hang in the balance", "v", "불확실한 상태이다", "The fate of the bill hangs in the balance."),
    ("be in the spotlight", "v", "주목받다", "The city is in the global spotlight."),
    ("draw attention", "v", "주목을 끌다", "The report has drawn international attention."),
    ("stoke", "v", "부추기다", "The speech stoked fears of a recession."),
    ("inflame", "v", "선동하다, 악화시키다", "The comments inflamed tensions."),
    ("defuse", "v", "긴장을 완화하다", "Diplomats worked to defuse the crisis."),
    ("broker", "v", "중재하다", "The US brokered a peace deal."),
    ("mediate", "v", "중재하다", "The UN mediated between the two sides."),
    ("facilitate", "v", "촉진하다", "The talks were facilitated by a neutral party."),
    ("broker a deal", "v", "협상을 타결하다", "They finally brokered a deal."),
    ("clinch", "v", "확보하다, 체결하다", "She clinched the nomination on the first ballot."),
    ("seal", "v", "확정하다", "The agreement was sealed with a handshake."),
    ("ratify", "v", "비준하다", "The treaty was ratified by all member states."),
    ("enforce", "v", "집행하다", "The law is difficult to enforce."),
    ("implement", "v", "시행하다", "The policy will be implemented next year."),
    ("roll back", "v", "철회하다", "The new government rolled back previous reforms."),
    ("scrap", "v", "폐기하다", "Plans were scrapped due to cost overruns."),
    ("shelve", "v", "보류하다", "The project was shelved indefinitely."),
    ("fast-track", "v", "신속하게 처리하다", "The bill was fast-tracked through Parliament."),
    ("push through", "v", "밀어붙이다", "The ruling party pushed the bill through."),
    ("block", "v", "막다", "The senate blocked the nomination."),
    ("stall", "v", "지연시키다", "Opponents tried to stall the legislation."),
    ("derail", "v", "탈선시키다", "Protests threatened to derail the summit."),
    ("jeopardize", "v", "위태롭게 하다", "The scandal jeopardized the peace talks."),
    ("salvage", "v", "수습하다", "He tried to salvage his reputation."),
    ("overshadow", "v", "빛을 가리다", "The scandal overshadowed the summit."),
    ("dominate", "v", "장악하다", "The story dominated the news cycle."),
    ("capture the headlines", "v", "헤드라인을 장식하다", "The story captured headlines worldwide."),
    ("make headlines", "v", "화제가 되다", "The incident made international headlines."),
    ("break the silence", "v", "침묵을 깨다", "She finally broke her silence."),
    ("go public", "v", "공개하다", "He decided to go public with the allegations."),
    ("go on record", "v", "공식 발언하다", "She went on record opposing the deal."),
    ("off the record", "phrase", "비공개로", "He said, off the record, that he was resigning."),
    ("source close to", "phrase", "측근에 따르면", "Sources close to the president denied the claim."),
    ("according to", "phrase", "~에 따르면", "According to officials, talks are ongoing."),
    ("it is understood that", "phrase", "알려진 바에 따르면", "It is understood that a deal is close."),
    ("amid growing", "phrase", "고조되는 ~ 속에", "The decision came amid growing criticism."),
    ("in a statement", "phrase", "성명에서", "In a statement, the minister said.."),
    ("cited", "v", "인용됐다", "Officials cited security reasons for the move."),
    ("a spokesman said", "phrase", "대변인은 밝혔다", "A Kremlin spokesman said no talks were planned."),

    # ── 보충 어휘 (일상 + 정치·사회 혼합) ──────────────────────────────────

    # 설득 / 논쟁 / 토론
    ("rebut", "v", "반박하다", "She rebutted his claims with clear evidence."),
    ("refute", "v", "논리적으로 반박하다", "The scientist refuted the popular theory."),
    ("counter", "v/n", "반박하다 / 반론", "He countered with a strong argument."),
    ("contend", "v", "주장하다", "Critics contend that the policy is misguided."),
    ("concede", "v", "인정하다", "I concede that you have a point."),
    ("substantiate", "v", "뒷받침하다", "He failed to substantiate his claims."),
    ("corroborate", "v", "확증하다", "Multiple witnesses corroborated the story."),
    ("contradict", "v", "모순되다", "The new evidence contradicts earlier reports."),
    ("challenge", "v", "이의를 제기하다", "The lawyer challenged the witness's account."),
    ("scrutinize", "v", "면밀히 따지다", "The media scrutinized every word."),
    ("question", "v", "의문을 제기하다", "Experts have questioned the methodology."),
    ("dispute", "v", "반박하다", "The government disputes those figures."),
    ("dismiss", "v", "일축하다", "He dismissed the allegations as baseless."),
    ("downplay", "v", "축소하다", "Officials downplayed the severity of the crisis."),
    ("overstate", "v", "과장하다", "The risks were overstated by the media."),
    ("understate", "v", "축소하다", "He understated the scale of the problem."),
    ("overplay", "v", "과장하다", "They overplayed their hand in negotiations."),
    ("acknowledge", "v", "인정하다", "She acknowledged the mistake publicly."),
    ("admit", "v", "인정하다", "He admitted he had been wrong."),
    ("backtrack", "v", "물러나다, 입장을 바꾸다", "She was forced to backtrack on her promise."),
    ("clarify", "v", "명확히 하다", "Please clarify what you meant."),
    ("elaborate", "v", "자세히 설명하다", "Could you elaborate on that point?"),
    ("articulate", "v", "명확히 표현하다", "She articulated her position clearly."),
    ("advocate", "v", "주장하다, 지지하다", "He advocates for stronger gun laws."),
    ("champion", "v", "적극 지지하다", "She has championed workers' rights for decades."),
    ("push for", "v", "강력히 요구하다", "Unions are pushing for a four-day workweek."),
    ("lobby for", "v", "로비하다", "Pharmaceutical companies lobby heavily for favorable rules."),
    ("campaign for", "v", "운동하다", "She campaigned for free university education."),
    ("oppose", "v", "반대하다", "Several lawmakers openly opposed the bill."),
    ("resist", "v", "저항하다", "Communities resisted the gentrification project."),
    ("block", "v", "차단하다", "The move was blocked by the senate."),
    ("obstruct", "v", "방해하다", "He was accused of obstructing justice."),
    ("sabotage", "v", "방해 공작을 하다", "Insiders allegedly sabotaged the project."),
    ("interfere", "v", "개입하다", "Russia allegedly interfered in the election."),
    ("meddle", "v", "참견하다", "Foreign powers meddled in domestic affairs."),
    ("intervene", "v", "개입하다", "The international community intervened."),
    ("retaliate", "v", "보복하다", "The country threatened to retaliate."),
    ("reciprocate", "v", "상호 대응하다", "Both sides agreed to reciprocate trade concessions."),
    ("penalize", "v", "제재하다, 처벌하다", "Firms that pollute should be penalized."),

    # 경제 관련 실생활 어휘
    ("inflation", "n", "인플레이션", "Rising inflation is hitting households hard."),
    ("recession", "n", "경기 침체", "Economists fear a recession is coming."),
    ("stagnation", "n", "정체", "Economic stagnation has lasted a decade."),
    ("boom", "n/v", "호황 / 호황이다", "The tech sector is experiencing a boom."),
    ("bust", "n", "불황", "After every boom comes a bust."),
    ("bail out", "v", "구제하다", "The government bailed out the failing bank."),
    ("default", "v/n", "채무 불이행하다 / 채무 불이행", "The country defaulted on its debt."),
    ("austerity", "n", "긴축", "Austerity cuts sparked mass protests."),
    ("quantitative easing", "n", "양적 완화", "The central bank launched quantitative easing."),
    ("interest rate", "n", "이자율", "The central bank raised interest rates."),
    ("tariff", "n", "관세", "New tariffs hit the auto industry hard."),
    ("trade war", "n", "무역 전쟁", "The trade war disrupted global supply chains."),
    ("supply chain", "n", "공급망", "The pandemic exposed weaknesses in the supply chain."),
    ("outsource", "v", "외주화하다", "Jobs were outsourced to cheaper markets."),
    ("offshore", "v", "해외로 이전하다", "Many companies offshore their production."),
    ("monopoly", "n", "독점", "Regulators are concerned about tech monopolies."),
    ("oligopoly", "n", "과점", "A small oligopoly controls the market."),
    ("cartel", "n", "카르텔", "The oil cartel agreed to cut production."),
    ("antitrust", "adj", "독점 금지의", "Antitrust regulators launched an investigation."),
    ("regulate", "v", "규제하다", "Big tech needs to be more tightly regulated."),
    ("deregulate", "v", "규제를 완화하다", "Critics warned against deregulating the banks."),
    ("inequality", "n", "불평등", "Growing inequality threatens social stability."),
    ("redistribution", "n", "재분배", "The party supports redistribution of wealth."),
    ("progressive tax", "n", "누진세", "A progressive tax system is considered fairer."),
    ("flat tax", "n", "단일 세율", "Some economists favor a flat tax."),
    ("tax avoidance", "n", "절세", "Aggressive tax avoidance by corporations is legal but controversial."),
    ("tax evasion", "n", "탈세", "He was charged with tax evasion."),
    ("offshore account", "n", "해외 계좌", "Offshore accounts were revealed in the leak."),
    ("shell company", "n", "유령 회사", "The money was routed through shell companies."),
    ("dark money", "n", "다크 머니", "Dark money flooded the election campaign."),
    ("crowdfund", "v", "크라우드 펀딩하다", "They crowdfunded the documentary."),
    ("startup", "n", "스타트업", "The startup raised millions in its first round."),
    ("unicorn", "n", "유니콘 기업", "The app became a unicorn within two years."),
    ("venture capital", "n", "벤처 캐피탈", "Venture capital poured into AI companies."),
    ("IPO", "n", "기업 공개", "The IPO valued the company at $10 billion."),
    ("stock market", "n", "주식 시장", "The stock market reacted badly to the news."),
    ("volatility", "n", "변동성", "High volatility is making investors nervous."),
    ("bear market", "n", "약세장", "We may be entering a prolonged bear market."),
    ("bull market", "n", "강세장", "The bull market lasted for over a decade."),
    ("hedge fund", "n", "헤지펀드", "Hedge funds bet against the currency."),
    ("sovereign debt", "n", "국가 부채", "Sovereign debt levels have reached a record."),

    # 테크놀로지 / AI 사회 영향
    ("artificial intelligence", "n", "인공지능", "Artificial intelligence is reshaping the economy."),
    ("automation", "n", "자동화", "Automation is displacing millions of jobs."),
    ("algorithm", "n", "알고리즘", "The algorithm determines what you see online."),
    ("data privacy", "n", "데이터 프라이버시", "Data privacy laws vary widely across countries."),
    ("cybersecurity", "n", "사이버 보안", "Cybersecurity threats are growing rapidly."),
    ("hack", "v/n", "해킹하다 / 해킹", "Government systems were hacked."),
    ("deepfake", "n", "딥페이크", "Deepfake videos are being used in propaganda."),
    ("misinformation", "n", "잘못된 정보", "Misinformation is a major challenge."),
    ("digital divide", "n", "디지털 격차", "The digital divide affects rural communities."),
    ("screen time", "n", "화면 노출 시간", "Concerns about children's screen time are rising."),
    ("attention economy", "n", "관심 경제", "Social media profits from the attention economy."),
    ("platform", "n", "플랫폼", "Tech platforms wield enormous power."),
    ("big tech", "n", "빅테크", "Big tech companies are under regulatory pressure."),
    ("regulate AI", "v", "AI를 규제하다", "Governments are scrambling to regulate AI."),
    ("facial recognition", "n", "안면 인식", "Facial recognition raises privacy concerns."),
    ("drone", "n", "드론", "Drones were used to track protesters."),
    ("surveillance state", "n", "감시 국가", "Critics warn of a growing surveillance state."),
    ("net neutrality", "n", "망 중립성", "Net neutrality protects open internet access."),
    ("right to be forgotten", "n", "잊힐 권리", "The right to be forgotten is a legal concept in the EU."),
    ("digital footprint", "n", "디지털 발자국", "Your digital footprint can reveal a lot."),

    # 일상 회화 고급 표현
    ("acknowledge the elephant", "phrase", "공공연한 사실을 인정하다", "We need to acknowledge the elephant in the room."),
    ("get the ball rolling", "phrase", "시작하다", "Let's get the ball rolling on this project."),
    ("hit the nail on the head", "phrase", "정확히 짚다", "You hit the nail on the head."),
    ("miss the point", "phrase", "요점을 놓치다", "I think you're missing the point entirely."),
    ("see eye to eye", "phrase", "의견이 일치하다", "We don't always see eye to eye."),
    ("be on the same wavelength", "phrase", "생각이 통하다", "We're on the same wavelength on this."),
    ("talk past each other", "phrase", "서로 딴 소리를 하다", "They're just talking past each other."),
    ("agree to disagree", "phrase", "의견 차이를 인정하다", "We agreed to disagree and move on."),
    ("find common ground", "phrase", "공통점을 찾다", "The key is to find common ground."),
    ("think outside the box", "phrase", "창의적으로 생각하다", "We need to think outside the box."),
    ("sit on the same side", "phrase", "같은 편이다", "Remember, we're on the same side here."),
    ("under the radar", "phrase", "주목받지 않고", "The story flew under the radar at first."),
    ("go off the rails", "phrase", "잘못되다", "The negotiation went completely off the rails."),
    ("off to a good start", "phrase", "좋은 출발을 하다", "The new initiative is off to a good start."),
    ("get off on the wrong foot", "phrase", "첫 단추를 잘못 끼우다", "They got off on the wrong foot."),
    ("pick up the pieces", "phrase", "수습하다", "Someone has to pick up the pieces."),
    ("on a roll", "phrase", "잘 풀리다", "Things are going great — we're on a roll."),
    ("hit a wall", "phrase", "벽에 부딪히다", "The investigation hit a wall."),
    ("a lot on one's plate", "phrase", "할 일이 많다", "I already have a lot on my plate."),
    ("behind the scenes", "phrase", "무대 뒤에서", "Behind the scenes, talks are ongoing."),
    ("in the pipeline", "phrase", "진행 중인", "Several reforms are in the pipeline."),
    ("on the agenda", "phrase", "안건에 있는", "Climate is high on the agenda."),
    ("off the agenda", "phrase", "제외된", "Tax hikes are off the agenda for now."),
    ("not on my watch", "phrase", "내가 있는 한 안 된다", "Not on my watch — I'll block it."),
    ("in somebody's corner", "phrase", "~의 편이다", "I'm in your corner no matter what."),
    ("have an axe to grind", "phrase", "개인적인 동기가 있다", "She has an axe to grind with the party."),
    ("put your money where your mouth is", "phrase", "말만 하지 말고 행동하다", "It's time to put your money where your mouth is."),
    ("read the room", "phrase", "분위기를 파악하다", "You need to learn to read the room."),
    ("punch above one's weight", "phrase", "자신보다 강한 상대와 맞서다", "The small nation punches above its weight diplomatically."),
    ("have skin in the game", "phrase", "직접적인 이해관계가 있다", "Politicians should have skin in the game."),
    ("move the needle", "phrase", "변화를 일으키다", "The policy barely moved the needle."),
    ("game changer", "n", "판을 바꾸는 것", "Renewable energy could be a game changer."),
    ("dealbreaker", "n", "협상을 깨는 요소", "That condition is a total dealbreaker."),
    ("window dressing", "n", "겉치레", "The reform was mere window dressing."),
    ("lip service", "n", "말뿐인 지지", "Politicians pay lip service to climate action."),
    ("optics", "n", "외적 이미지", "The optics of that decision were terrible."),
    ("talking point", "n", "핵심 논점", "That's a standard talking point from the party."),
    ("smoke and mirrors", "phrase", "눈 가리기", "The whole proposal was smoke and mirrors."),
    ("empty promise", "n", "공약 불이행", "Voters are tired of empty promises."),
    ("band-aid solution", "n", "임시방편", "That's just a band-aid solution."),
    ("root cause", "n", "근본 원인", "We need to address the root cause."),
    ("vicious cycle", "n", "악순환", "Poverty and poor health form a vicious cycle."),
    ("turning point", "n", "전환점", "This could be a real turning point."),
    ("silver lining", "n", "한 줄기 희망", "Even in crisis, there's a silver lining."),
    ("mixed bag", "n", "뒤섞인 결과", "The results were a mixed bag."),
    ("wake-up call", "n", "경각심을 일깨우는 계기", "The disaster was a wake-up call."),
    ("litmus test", "n", "리트머스 시험지 같은 기준", "This vote will be a litmus test for the party."),
    ("slippery slope", "n", "미끄러운 경사면", "Restrictions on speech are a slippery slope."),
    ("catch-22", "n", "진퇴양난", "It's a real catch-22 situation."),
    ("double standard", "n", "이중 잣대", "There's clearly a double standard at play."),
    ("red herring", "n", "엉뚱한 주제로 주의 분산", "That argument is a red herring."),
    ("straw man", "n", "허수아비 논증", "He's attacking a straw man, not my actual argument."),
    ("false dichotomy", "n", "거짓 이분법", "That's a false dichotomy."),
    ("circular argument", "n", "순환 논리", "His reasoning is a circular argument."),
    ("non sequitur", "n", "논리적 비약", "That conclusion is a complete non sequitur."),
    ("ad hominem", "n", "인신공격", "The debate devolved into ad hominem attacks."),
    ("precedent-setting", "adj", "선례를 세우는", "It was a precedent-setting court ruling."),
    ("status quo", "n", "현상 유지", "The election changed the status quo."),
    ("quo", "n", "현 상태", "Maintaining the quo is no longer an option."),
    ("trade-off", "n", "상충 관계", "Every policy involves a trade-off."),
    ("tipping point", "n", "임계점", "We may have already reached the tipping point."),
    ("paradigm shift", "n", "패러다임 전환", "AI represents a paradigm shift in labor."),
    ("bottom-up", "adj", "아래에서 위로의", "A bottom-up approach empowers communities."),
    ("top-down", "adj", "위에서 아래로의", "The top-down policy was poorly received."),
    ("bipartisan", "adj", "초당파적인", "The bill had rare bipartisan support."),
    ("zero-sum", "adj", "제로섬의", "Politics doesn't have to be zero-sum."),
    ("grassroots campaign", "n", "풀뿌리 운동", "A grassroots campaign challenged the incumbent."),
    ("check and balance", "n", "견제와 균형", "Checks and balances prevent power abuse."),
    ("moral high ground", "n", "도덕적 우위", "Both sides claim the moral high ground."),
    ("informed consent", "n", "사전 동의", "Informed consent is a core ethical principle."),
    ("proportional", "adj", "비례적인", "The response must be proportional to the threat."),
    ("escalation", "n", "고조", "Further escalation must be avoided."),
    ("de-escalate", "v", "긴장을 낮추다", "Both sides agreed to de-escalate."),
    ("deterrent", "n", "억지력", "The law serves as a deterrent."),
    ("leverage", "n", "지렛대, 영향력", "They used economic leverage in the talks."),
    ("flashpoint", "n", "분쟁의 불씨", "The region remains a geopolitical flashpoint."),
]



